applications/empleados/urls.py
from django.urls import path
from . import views

app_name = "empleados_app"

urlpatterns = [
    path('', views.InitialView.as_view()),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'),
    path(
        'listar-empleados-admin/',
        views.ListEmpleadosAdmin.as_view(),
        name='empleados_admin'),
    path('listar-by-area/<short_name>/',
         views.ListByAreaEmpleado.as_view(), name='empleados_by_departamento'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view(),),
    path('habilidades/', views.ListHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detalle'),

    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='update_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='delete_empleado'),
]

miproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from applications.departamentos.models import Departamento
from ckeditor.fields import RichTextField


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self) -> str:
        return self.habilidad


class Empleado(models.Model):
    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    )
    first_name = models.CharField('Nombres', max_length=255)
    last_name = models.CharField('Apellidos', max_length=255)
    full_name = models.CharField(
        'Nombres completos', max_length=255, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(
        'Avatar', upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['first_name', 'last_name']
        unique_together = ('first_name', 'last_name')

    def __str__(self) -> str:
        return self.first_name+' '+self.last_name

applications/empleados/forms.py
from django import forms

from .models import Empleado


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleados/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import (
    ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView)

from .models import Empleado
from .forms import EmpleadoForm


class InitialView(TemplateView):
    template_name = 'inicio.html'


class ListAllEmpleados(ListView):
    template_name = 'empleados/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self) -> QuerySet[Any]:
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista


class ListByAreaEmpleado(ListView):
    template_name = 'empleados/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self) -> QuerySet[Any]:
        area = self.kwargs['short_name']
        lista = Empleado.objects.filter(
            departamento__name=area
        )
        return lista


# class ListByAreaEmpleado(ListView):
#     template_name = 'empleados/list_by_area.html'

#     def get_queryset(self) -> QuerySet[Any]:
#         area = self.kwargs['short_name']
#         lista = Empleado.objects.filter(
#             departamento__name=area
#         )
#         return lista


class ListEmpleadosByKword(ListView):
    template_name = 'empleados/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self) -> QuerySet[Any]:
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista


class ListHabilidadesEmpleados(ListView):
    template_name = 'empleados/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self) -> QuerySet[Any]:
        empleado = Empleado.objects.get(id=1)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleados/detalle_empleado.html"
    context_object_name = 'empleado'

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        empleado = self.object  # Acceder al objeto Empleado actual
        context['habilidades'] = empleado.habilidades.all()
        return context


class SuccessView(TemplateView):
    template_name = "empleados/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleados/add.html"
    form_class = EmpleadoForm
    # fields = ['first_name', 'last_name', 'job',
    #           'departamento', 'habilidades', 'avatar']
    success_url = reverse_lazy('empleados_app:empleados_all')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleados/update.html"
    fields = ['first_name', 'last_name', 'job',
              'departamento', 'habilidades', 'avatar']
    success_url = reverse_lazy('empleados_app:empleados_all')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleados/delete.html"
    success_url = reverse_lazy('empleados_app:empleados_all')
    context_object_name = 'empleado'

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)


class ListEmpleadosAdmin(ListView):
    template_name = 'empleados/list_empleados.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

templates/empleados/add.html
{% extends 'base.html' %}


{% block title %}
    Registrar Empleado
{% endblock title %}
    

{% block content %}
    
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registar empleado</h1>
            <form class="cell" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                
                <div class="large-6 cell">
                    <label for="">Nombres: 
                        {{ form.first_name }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Apellido: 
                        {{ form.last_name }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Trabajo:
                        {{ form.job }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Departamento: 
                        {{ form.departamento }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">habilidades: 
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label for="">Avatar: 
                        {{ form.avatar }}
                    </label>
                </div>
                <button type="submit" class="success button">Agregar</button>
            </form>
        </div>

    </div>


    
{% endblock content %}
    

templates/empleados/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Buscar empleados por palabra clave</h1>
    <form action="" method="GET">
        {% csrf_token %}
        <input type="text" id="kword" name="kword" placeholder="ingrese nombre">
        <button type="submit">Buscar</button>
    </form>
    <br>
    {% for e in empleados %}
        <li>{{ e }}</li>
    {% endfor %}
        
</body>
</html>

templates/empleados/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}
    

{% block content %}
    
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1>Eliminar empleado: {{ empleado.full_name }}</h1>

            <form class="cell" action="" method="post">
                {% csrf_token %}
                <div class="callout secondary">

                    <p>confirme que desea Eliminar</p>
                    <button type="submit" class="alert button">Confirmar</button>
                </div>
            </form>            
        </div>
    </div>

{% endblock content %}
    

templates/empleados/detalle_empleado.html
{% extends 'base.html' %}

{% load static  %}
{% block title %}
    {{ empleado }}
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}


    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">


            <div class="cell large-4 card" style="width: 300px;">
                <div class="card-divider">
                    {{empleado.get_job_display }}
                </div>
                
                {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
                 {% else %}
                 <img src="{% static 'image/slider-01.jpg' %}">
                {% endif %}
                    
                <div class="card-section">
                    <h4>{{ empleado }}</h4>
                    <p>{{empleado.first_name}}</p>
                    <p>{{empleado.last_name}}</p>
                    <p>{{empleado.departamento.short_name }}</p>
                    <p><span class="label">Habilidades</span></p>
                        <ul class="vertical menu">
                        {% for h in empleado.habilidades.all %}
                            <li>{{ h.habilidad }}</li>
                        {% endfor %}
                        </ul>                    
                </div>
              </div>
        </div>
    </div>


        

{% endblock content %}

templates/empleados/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>habilidades</h1>
    <!-- <form action="" method="GET">
        {% csrf_token %}
        <input type="text" id="kword" name="kword" placeholder="ingrese nombre">
        <button type="submit">Buscar</button>
    </form> -->
    <br>
    <!-- {{ habilidades }} -->
    {% for e in habilidades %}
        <li>{{ e }}</li>
    {% endfor %}
        
</body>
</html>

templates/empleados/list_all.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}

    <div class="grid-container">

        <div class="grid-x">
            <h1 class="cell">Lista de empleados</h1>
            
            <form class="cell grid-x grid-margin-x" method="GET">
                <div class="cell large-7">
                        {% csrf_token %}
                        <input type="text" id="kword" name="kword" placeholder="buscar empleado">
                    </div>
                    <div class="cell large-2">
                        <button type="submit" class="success button">Buscar</button>
                    </div>
            </form>

            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Acción</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                            <tr>
                                <td>{{ e.id }}</td>
                                <td>{{ e.first_name }}</td>
                                <td>{{ e.last_name }}</td>
                                <td>{{ e.departamento }}</td>
                                <td>
                                    <a class="button warning" href="{% url 'empleados_app:empleado_detalle' e.id %}">Ver</a>
                                </td>
                            </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{ page_obj.previous_page_number }}">Previuos</a>
                                </li>
                            {% endif %}

                            
                            {% for pagina in paginator.page_range %}

                                {% if pagina != page_obj.number %} 
                                    <li class="">
                                {% else %}
                                    <li class="current">
                                {% endif %}
                                    
                                    <a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a>
                                </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="pagination-next">
                                    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next </a>
                                </li>
                            {% endif %}
                                
                                

                        

                        </ul>
                    </nav>                    
                {% endif %}
            </div>

        </div>

 
    </div>


{% endblock content %}
    

    

templates/empleados/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    Lista Departamento
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Departamento</h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>



        </div>
    </div>
</div>
    
{% endblock content %}
        

templates/empleados/list_empleados.html
{% extends 'base.html' %}

{% block content %}

{% include 'includes/header.html' %}

    <div class="grid-container">

        <div class="grid-x">
            <h1 class="cell">Lista de empleados</h1>
            


            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">Id</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Acción</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                            <tr>
                                <td>{{ e.id }}</td>
                                <td>{{ e.first_name }}</td>
                                <td>{{ e.last_name }}</td>
                                <td>{{ e.departamento }}</td>
                                <td class="grid-container">
                                    <div class=" grid-x ">
                                        <a class="cell button success" href="{% url 'empleados_app:update_empleado' e.id %}">Editar</a>
                                        <a class="cell button alert" href="{% url 'empleados_app:delete_empleado' e.id %}">Eliminar</a>

                                    </div>
                                </td>
                            </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            
                            {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{ page_obj.previous_page_number }}">Previuos</a>
                                </li>
                            {% endif %}

                            
                            {% for pagina in paginator.page_range %}

                                {% if pagina != page_obj.number %} 
                                    <li class="">
                                {% else %}
                                    <li class="current">
                                {% endif %}
                                    
                                    <a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a>
                                </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="pagination-next">
                                    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next </a>
                                </li>
                            {% endif %}
                                
                                

                        

                        </ul>
                    </nav>                    
                {% endif %}
            </div>

        </div>

 
    </div>


{% endblock content %}
    

    

templates/empleados/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Felicitaciones se guardó correctamente el empleado</h1>


        
</body>
</html>

templates/empleados/update.html
{% extends 'base.html' %}


{% block title %}
    Lista Departamento
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1>Actualizar empleado</h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" action="" method="POST" enctype="multipart/form-data">

                {% csrf_token %}

                <div class="large-6 cell">
                    <label for="">Nombres: 
                        {{ form.first_name }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Apellido: 
                        {{ form.last_name }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Trabajo:
                        {{ form.job }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Departamento: 
                        {{ form.departamento }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">habilidades: 
                        {{ form.habilidades }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Avatar: 
                        {{ form.avatar }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>

            </form>
        </div>
    </div>
</div>
    
{% endblock content %}




        
</body>
</html>