applications/departamentos/urls.py
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(),
         name='new_departamento'),
    path(
        'lista-departamento/',
        views.DepartamentoListView.as_view(),
        name='lista_departamento'),
]

applications/empleados/urls.py
from django.urls import path
from . import views

app_name = "empleados_app"

urlpatterns = [
    path('', views.InitialView.as_view()),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'),
    path(
        'listar-empleados-admin/',
        views.ListEmpleadosAdmin.as_view(),
        name='empleados_admin'),
    path('listar-by-area/<short_name>/',
         views.ListByAreaEmpleado.as_view(), name='empleados_by_departamento'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view(),),
    path('habilidades/', views.ListHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detalle'),

    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='update_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='delete_empleado'),
]

miproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamentos/models.py
from django.db import models

# Create your models here.


class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=255)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de las empresa'
        ordering = ['-name']
        unique_together = ('name', 'short_name')

    def __str__(self) -> str:
        return self.name

applications/departamentos/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=20)

applications/departamentos/views.py
from django.http import HttpResponse
from django.shortcuts import render

# from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import NewDepartamentoForm

from applications.empleados.models import Empleado
from applications.departamentos.models import Departamento


class NewDepartamentoView(FormView):
    template_name = 'departamentos/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form) -> HttpResponse:

        dpto = Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
        dpto.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job=1,
            departamento=dpto
        )
        return super(NewDepartamentoView, self).form_valid(form)


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamentos/lista-departamento.html"
    context_object_name = 'departamentos'

templates/departamentos/lista-departamento.html
{% extends 'base.html' %}


{% block title %}
    Lista Departamento
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Departamento</h1>
        <div class="cell">
            <table>
                <tbody>
                    
                    {% for departamento  in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.short_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'empleados_app:empleados_by_departamento' departamento.short_name %}">Ver</a>
                            </td>
                        </tr>                        
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
    
{% endblock content %}
    

templates/departamentos/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Registrar Empleado
{% endblock title %}
    

{% block content %}
    
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">New Departamento</h1>
            <form class="cell callout grid-x grid-margin-x" action="" method="post">
                {% csrf_token %}
                <h3>Datos Empleados</h3>
                <div class="large-6 cell">
                    <label for="">Nombres: 
                        {{ form.nombre }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Apellido: 
                        {{ form.apellido }}
                    </label>
                </div>

                <h3>Datos Departamento</h3>
                <div class="large-6 cell">
                    <label for="">Departamento: 
                        {{ form.departamento }}
                    </label>
                </div>

                <div class="large-6 cell">
                    <label for="">Nombre corto: 
                        {{ form.short_name }}
                    </label>
                </div>

                <button type="submit" class="success button">Agregar</button>
            </form>
        </div>

    </div>




    
{% endblock content %}