applications/departamentos/urls.py
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(),
         name='new_departamento'),
    path(
        'lista-departamento/',
        views.DepartamentoListView.as_view(),
        name='lista_departamento'),
]

applications/empleados/urls.py
from django.urls import path
from . import views

app_name = "empleados_app"

urlpatterns = [
    path('', views.InitialView.as_view()),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'),
    path(
        'listar-empleados-admin/',
        views.ListEmpleadosAdmin.as_view(),
        name='empleados_admin'),
    path('listar-by-area/<short_name>/',
         views.ListByAreaEmpleado.as_view(), name='empleados_by_departamento'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view(),),
    path('habilidades/', views.ListHabilidadesEmpleados.as_view()),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detalle'),

    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='update_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='delete_empleado'),
]

miproyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'empleados_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamento</a></li>
        <li><a href="{% url 'empleados_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:new_departamento' %}">Nuevo Departamento</a></li>

      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a  class="button"href="{% url 'empleados_app:empleado_add' %}">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>